#4: add information about instead-js
ForNeVeR/old-mixer-tales pull request #15
Opened 2017-03-14 16:17 UTC by ForNeVeR

Closes #4.

/cc @Minoru

2017-03-14 17:59 UTC, Minoru requested changes

2017-03-14 17:59 UTC, Minoru commented on Readme.md
> +There's an [instead-js] project we also support. To run it, follow the
THERE CAN BE ONLY ONE— Erm, sorry; I mean, there is only one "instead-js" project, so definitive article should be used.

"Running" a project means managing it; not what you intended to say, I guess.

I suggest to rewrite these as follows: "The game can also be run inside a webclient provided by the [intead-js] project. To do so, …".

2017-03-14 17:59 UTC, Minoru commented on Readme.md
> +instructions in the instead-js repository. Here's a quick excerpt:
Couldn't find an authoritative source for that, but in my understanding, excerpts can't be "quick". I found this [list of alternatives](http://adjective1.com/for-excerpt/).

Age-old Google test corroborates:
* ["quick excerpt"](https://encrypted.google.com/search?hl=en&q="quick%20excerpt") — 33,300 results;
* ["brief excerpt"](https://encrypted.google.com/search?hl=en&q="brief%20excerpt") — 337,000 results;
* ["small excerpt"](https://encrypted.google.com/search?hl=en&q="small+excerpt") — 410,000 results.

Finally, what you provide is more of a gist than an excerpt.

2017-03-15 07:00 UTC, ForNeVeR commented
Thanks for the review!

2017-03-15 07:01 UTC, merged